export const mainProjects = [
  {
    id: "boink",
    title: "Bo!nk",
    year: "2021",
    description: "A Windows Vista-inspired inkball game published on the App Store",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-OFGQDkrP2BvNmhLieOxExwEZBsCGcq.png",
    logo: "/images/boink-logo.webp",
    tags: ["iOS", "Swift", "Game Development"],
    colors: "#417193",
  },
  {
    id: "fatherfigure",
    title: "Father Figure",
    year: "2025",
    description: "A virtual father Chrome extension you never knew you needed",
    image: "https://raw.githubusercontent.com/fiof25/father-figure-htn/refs/heads/main/assets/fatherfigurebanner.png",
    logo: "https://raw.githubusercontent.com/fiof25/father-figure-htn/refs/heads/main/assets/Logo.png",
    tags: ["Chrome Extension", "JS", "Utilities"],
    colors: "#673435",
  },
  {
    id: "salespatriot",
    title: "SalesPatriot (YC W25)",
    year: "2025",
    description: "Completing an end-to-end UX for defense manufacturers",
    image: "https://richardli-1.github.io/Old-Personal-Website/salespatriott.png?height=400&width=600",
    tags: ["Internship", "UI/UX", "AI"],
    colors: "#352F0C",
  },
  {
    id: "futureforward",
    title: "Future Forward",
    year: "2024-2025",
    description: "Non-profit focusing on helping students discover their vocations",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ffbanner.png-JMScQeCriXKG0sG0z3bc8GFrra41av.jpeg",
    image2: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Frame%203.png-jKOva7clSQUCHgEUorDDX86vX0w3Me.jpeg",
    image3: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Frame%204.png-NMSo9ZL9dNWIiNEavhdNlELQycDNz9.jpeg",

    logo: "/images/future-forward-logo.png",
    tags: ["Non-profit", "Project Management", "Community"],
    colors: "#3B369C",
  },
  // {
  //   id: "classprofile",
  //   title: "SYDE Class of 2030 Profile",
  //   year: "2025",
  //   description: "WIP project...",
  //   image: "",
  //   logo: "",
  //   tags: ["Community", "Web Development", "Data"],
  //   colors: "",
  // },
  {
    id: "yrhacks",
    title: "YRHacks",
    year: "2024-2025",
    description: "Organized Canada's largest high school hackathon",
    image: "https://richardli-1.github.io/Old-Personal-Website/YRHacks%20banner.png",
    logo: "/images/yrhacks-logo.png",
    tags: ["Community", "Logistics", "Organizations"],
    colors: "#5744AF",
  },
  // {
  //   id: "cec",
  //   title: "Career Education Council",
  //   year: "2024-2025",
  //   description: "",
  //   image: "",
  //   logo: "/images/cec-logo.webp",
  //   tags: ["iOS", "Swift", "App Development"],
  //   colors: "#003DA5",
  // },
  {
    id: "4sight",
    title: "4sight",
    year: "2025",
    description: "Eye Tester App",
    image: "",
    logo: "/images/jamAsset.PNG",
    tags: ["iOS", "Swift", "App Development"],
    colors: "",
  },
]
