export const mainProjects = [
  {
    id: "boink",
    title: "Bo!nk",
    year: "2021",
    description: "A Windows Vista-inspired inkball game published on the App Store",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-OFGQDkrP2BvNmhLieOxExwEZBsCGcq.png",
    logo: "/images/boink-logo.webp",
    tags: ["iOS", "Swift", "Game Development"],
  },
  {
    id: "fatherfigure",
    title: "Father Figure",
    year: "2025",
    description: "A virtual father Chrome extension you never knew you needed",
    image: "https://raw.githubusercontent.com/fiof25/father-figure-htn/refs/heads/main/assets/fatherfigurebanner.png",
    logo: "https://raw.githubusercontent.com/fiof25/father-figure-htn/refs/heads/main/assets/Logo.png",
    tags: ["Chrome Extension", "JS", "Utilities"],
  },
  {
    id: "salespatriot",
    title: "SalesPatriot (YC W25)",
    year: "2025",
    description: "Completing an end-to-end UX for defense manufacturers",
    image: "https://richardli-1.github.io/Personal-Website/salespatriott.png?height=400&width=600",
    tags: ["Internship", "UI/UX", "AI"],
  },
  {
    id: "futureforward",
    title: "Future Forward",
    year: "2024-2025",
    description: "Non-profit focusing on helping students discover their vocations",
    image: "images/IMG_7745.jpeg",
    logo: "/images/future-forward-logo.png",
    tags: ["Non-profit", "Project Management", "Community"],
  },
  {
    id: "yrhacks",
    title: "YRHacks",
    year: "2024-2025",
    description: "Helped organize Canada's largest high school hackathon",
    image: "images/yrhacks crowd.jpeg",
    logo: "/images/yrhacks-logo.png",
    tags: ["Community", "Logistics", "Organizations"],
  },
  {
    id: "cec",
    title: "Career Education Council",
    year: "2024-2025",
    description: "",
    image: "",
    logo: "/images/cec-logo.webp",
    tags: ["iOS", "Swift", "App Development"],
  },
  {
    id: "4sight",
    title: "4sight",
    year: "2025",
    description: "Eye Tester App",
    image: "",
    logo: "/images/cec-logo.webp",
    tags: ["iOS", "Swift", "App Development"],
  },
]
